---

- name: check for python3
  shell: python3 --version
  failed_when: false
  register: result

- name: get python3
  when: result.rc != 0 or python3_version not in result.stdout
  block:
    - name: set python3 filename
      set_fact:
        filename: 'Python-{{ python3_version }}.tgz'
        build_path: '/tmp/Python-{{ python3_version }}'

    - name: download python3
      get_url:
        url: 'https://www.python.org/ftp/python/{{ python3_version }}/{{ filename }}'
        dest: '/tmp/{{ filename }}'

    - name: decompress python3
      unarchive:
        src: '/tmp/{{ filename }}'
        dest: '/tmp'

    - name: create python3 destinations
      file:
        path: '~/python/python3/{{ python3_version }}'
        state: directory
        recurse: true
        mode: u=rwx,g=rx,o=rx

    - name: build python3 from source
      block:
        - name: prepare python3 build
          shell: './configure --prefix=$HOME/python/python3/{{ python3_version }}/'
          args:
            chdir: '{{ build_path }}'

        - name: build python3
          shell: 'make {{ item }}'
          args:
            chdir: '{{ build_path }}'
          with_items:
            - all
            - install

    - name: create current python3 link
      file:
        src: '~/python/python3/{{ python3_version }}'
        dest: '~/python/python3/current'
        state: link
      notify: update python

- name: add python3 to path
  lineinfile:
    path: ~/.zshrc
    regexp: 'export PATH=.*'
    line: >-
      exports PATH="$HOME/python/python3/current/bin:$PATH"
