---

- name: install python optional requirements
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev

- name: install pythons
  include_tasks: install.yml
  with_items:
    - version: '{{ python2_version }}'
      python: python
      pip: pip
    - version: '{{ python3_version }}'
      python: python3
      pip: pip3

- name: install pipenv
  pip:
    name: pipenv
    state: latest
    executable: /opt/python3/current/bin/pip3
