---

- name: create git config path
  file:
    path: ~/.config/git
    state: directory

- name: git config
  template:
    src: gitconfig.j2
    dest: ~/.config/git/config
    mode: u=rwx,g=,o=

- name: git ignore
  copy:
    src: gitignore.txt
    dest: ~/.config/git/ignore
