---

- name: check for chrome
  shell: google-chrome --version
  failed_when: false
  register: result

- name: get chrome
  when: result.rc != 0
  block:
    - name: download chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb

    - name: install chrome
      become: true
      apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
