---

- name: install tmux
  become: true
  apt:
    name: tmux
    state: latest
    cache_valid_time: 3600  # 1 hour

- name: clone dotfiles
  git:
    repo: 'https://github.com/seanjh/dotfiles.git'
    dest: ~/dotfiles

- name: link tmux config to dotfiles
  copy:
    src: ~/dotfiles/tmux.conf
    dest: ~/.tmux.conf
