---

- name: install vim
  apt:
    name: vim
    state: latest
    cache_valid_time: 3600  # 1 hour

- name: clone dotfiles
  repo:
    repo: 'https://github.com/seanjh/dotfiles.git'
    dest: ~/dotfiles

- name: link vim config to dotfiles
  file:
    src: ~/dotfiles/vim
    dest: ~/.vim

- name: setup vundle
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git' 
    dest: ~/dotfiles/vim/bundle/Vundle.vim
    update: no
  register: clone

- name: install vim plugins
  shell: vim +PluginInstall +qall
  when: clone is changed
